# Generated by Django 5.1.3 on 2024-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerplots',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='playerplots',
            name='last_collection',
            field=models.DateTimeField(),
        ),
    ]
